### ISSUE TITLE
How to avoide Duplicate class issue 

### ISSUE THREAD

**Issue by gulabsagevadiya** [Lavmee/constraintlayout-compose-multiplatform#36] opened 2024-03-07 10:30 UTC
`Execution failed for task ':composeApp:checkDebugDuplicateClasses'.`
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.constraintlayout.core.ArrayLinkedVariables found in modules compose-release-runtime (tech.annexflow.compose:constraintlayout-compose-multiplatform-android:0.2.3) and constraintlayout-core-1.0 (androidx.constraintlayout:constraintlayout-core:1.0.0)
   
How to fix this issue while using with other lib which has different version of constraintlayout

**Comment by Lavmee** [comment] 2024-03-07 16:11
You need to use either multiplatform or android artifact. Cannot be used at the same time.

**Comment by dshatz** [comment] 2024-04-11 13:41
@Lavmee I would like to describe my usecase.

We have a large project with a pure android app that consumes a multiplatform compose library. The android app has standard constraintlayout in xml layouts, while the compose library uses this repo's constraintlayout in compose code.

We would like to be able to display composables from the library inside the android app but now it's not possible because the constraintlayout-core classes have the same names as the standard androidx library. 

What can be done about this? Perhaps change the package name of this library?

**Comment by dshatz** [comment] 2024-08-19 08:43
Is it possible to reopen this?
The PR is still waiting.

**Comment by Lavmee** [comment] 2024-08-25 12:26
Should be fixed in version 0.5.0-alpha03-shaded-core [PUBLISHING]. If there are any problems, write here.

**Comment by ismai117** [comment] 2024-08-31 06:18
I'm still receiving the same problem 

```
Execution failed for task ':app:checkDefaultDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class androidx.constraintlayout.compose.AnchorFunctions found in modules compose-release.aar -> jetified-compose-release-runtime (tech.annexflow.compose:constraintlayout-compose-multiplatform-android:0.5.0-alpha03-shaded-core) and constraintlayout-compose-1.0.1.aar -> jetified-constraintlayout-compose-1.0.1-runtime (androidx.constraintlayout:constraintlayout-compose:1.0.1)
     Duplicate class androidx.constraintlayout.compose.BaseHorizontalAnchorable found in modules compose-release.aar -> jetified-compose-release-runtime (tech.annexflow.compose:constraintlayout-compose-multiplatform-android:0.5.0-alpha03-shaded-core) and constraintlayout-compose-1.0.1.aar -> jetified-constraintlayout-compose-1.0.1-runtime (androidx.constraintlayout:constraintlayout-compose:1.0.1)
     Duplicate class androidx.constraintlayout.compose.BaseVerticalAnchorable found in modules compose-release.aar -> jetified-compose-release-runtime (tech.annexflow.compose:constraintlayout-compose-multiplatform-android:0.5.0-alpha03-shaded-core) and constraintlayout-compose-1.0.1.aar -> jetified-constraintlayout-compose-1.0.1-runtime (androidx.constraintlayout:constraintlayout-compose:1.0.1)
     Duplicate class androidx.constraintlayout.compose.BaselineAnchorable found in modules compose-release.aar -> jetified-compose-release-runtime (tech.annexflow.compose:constraintlayout-compose-multiplatform-android:0.5.0-alpha03-shaded-core) and constraintlayout-compose-1.0.1.aar -> jetified-constraintlayout-compose-1.0.1-runtime (androidx.constraintlayout:constraintlayout-compose:1.0.1)
     Duplicate class androidx.constraintlayout.compose.BaselineAnchorable$DefaultImpls found in modules compose-release.aar -> jetified-compose-release-runtime (tech.annexflow.compose:constraintlayout-compose-multiplatform-android:0.5.0-alpha03-shaded-core) and constraintlayout-compose-1.0.1.aar -> jetified-constraintlayout-compose-1.0.1-runtime (androidx.constraintlayout:constraintlayout-compose:1.0.1)
```

**Comment by Lavmee** [comment] 2024-08-31 12:19
@ismai117 can you send me the minimum reproducer?

**Comment by ismai117** [comment] 2024-09-01 10:22
@Lavmee I'm working on a multi-module project,  In our Android-specific modules, we're using (androidx.constraintlayout:constraintlayout-compose) However, in a Kotlin Multiplatform module, we're using your library (tech.annexflow.compose:constraintlayout-compose-multiplatform).

When I try to build the project, I encounter the error above

**Comment by dshatz** [comment] 2024-09-01 10:31
To add my two cents, I don't think I see any relevant commits for this issue. See my PR for what definitely helped (I know it's out of date, but you get the idea). 

I'll try to make a reproducible example for the latest version.

**Comment by Lavmee** [comment] 2024-09-01 13:31
@ismai117, if you need a library with a completely different package name, try version "0.5.0-alpha03-shaded"

**Comment by Lavmee** [comment] 2024-09-01 13:34
@dshatz Now the library has three versions, the usual one with androidx package (0.5.0-alpha03), with shaded core (0.5.0-alpha03-shaded-core), and completely shaded package (0.5.0-alpha03-shaded)

**Closed** 2024-09-15 08:07 UTC
